In [ ]:
from pathlib import Path
from sklearn.metrics import roc_auc_score
import pandas as pd

Root = Path("/Users/taehayeong/Desktop/PILAB/RobustnessAD/results/winclip")

classes = [
    "bottle", "cable", "capsule", "hazelnut", "metal_nut",
    "pill", "screw", "toothbrush", "transistor", "zipper",
    "wood", "tile", "grid", "leather", "carpet"
]

rows = []

for cls in classes:
    csv_path = Root / f"{cls}.csv"
    data = pd.read_csv(csv_path)

    score = roc_auc_score(data["label"], data["image_score"])
    rows.append({
        "class": cls,
        "I-AUROC": score
    })

df = pd.DataFrame(rows)
df.to_csv(Root / "auroc_mvtec.csv", index=False)
df = df.sort_values(by="I-AUROC", ascending=True)
df

         class   I-AUROC
1        cable  0.702774
5         pill  0.810966
6        screw  0.821070
7   toothbrush  0.852778
0       bottle  0.886508
2      capsule  0.895094
4    metal_nut  0.923754
8   transistor  0.938750
10        wood  0.969298
3     hazelnut  0.971786
12        grid  0.978279
9       zipper  0.983981
13     leather  0.998302
14      carpet  0.999599
11        tile  1.000000

In [ ]:
from pathlib import Path
from sklearn.metrics import roc_auc_score
import pandas as pd

Root = Path("/Users/taehayeong/Desktop/PILAB/RobustnessAD/results/winclip")

classes = [
    "candle", "capsules", "cashew", "chewinggum", "fryum",
    "macaroni1", "macaroni2", "pcb1", "pcb2", "pcb3",
    "pcb4", "pipe_fryum"
]

rows = []

for cls in classes:
    csv_path = Root / f"{cls}.csv"
    data = pd.read_csv(csv_path)

    score = roc_auc_score(data["label"], data["image_score"])
    rows.append({
        "class": cls,
        "I-AUROC": score,
    })

df = pd.DataFrame(rows)
df.to_csv(Root / "auroc_visa.csv", index=False)
df = df.sort_values(by="I-AUROC", ascending=True)
df

         class   I-AUROC
9         pcb3  0.616832
8         pcb2  0.620500
6    macaroni2  0.722100
2       cashew  0.759600
0       candle  0.809400
1     capsules  0.827833
7         pcb1  0.851900
5    macaroni1  0.867400
11  pipe_fryum  0.922800
4        fryum  0.927000
10        pcb4  0.938911
3   chewinggum  0.972200

In [16]:
import pandas as pd